# ------------------------------------------------------------------------------
# Make file for filesystem performance demonstration
# ------------------------------------------------------------------------------

.PHONY : all
all : do_perf_io_test

do_perf_io_test: do_perf_io_test.c
	gcc -o do_perf_io_test do_perf_io_test.c

