---
# ------------------------------------------------------------------------------
# Configure System Under Test (SUT) for use by HammerDB
# ------------------------------------------------------------------------------
- hosts:                all
  tasks:

  # ----------------------------------------------------------------------------
  # Load passwords from passwords/oracle.yml which has the following variables:
  # * pw_all
  # * pw_sys
  # * pw_system
  # * pw_pdbadmin
  #
  # >>>>>>> This file is deliberately NOT included in the GIT repository <<<<<<<
  # ----------------------------------------------------------------------------

  - name:               "Load passwords"
    include_vars:
      file:             "passwords/oracle.yml"
    no_log:             true

  - name:               "Install required packages from repositories"
    dnf:
      name:
        -               tcl
      state:            present
    become:             yes
    become_user:        root

  - name:               "Install required packages using PIP"
    pip:
      name:
        -               "cx_Oracle"
      state:            present
    become:             yes
    become_user:        root

  - name:               "Start Oracle Listener and Database Instance"
    include_tasks:      startup_db.yml

  - name:               "Create DB Configuration Scripts"
    template:
      dest:             "{{ item }}"
      src:              "{{ item | basename }}.j2"
      mode:             "u+rwx"
    with_items:
      -                 "{{ configure_sut_db }}"
      -                 "{{ count_tpcc_objects }}"
    become:             yes
    become_user:        oracle
    when:               inventory_hostname in groups['database']

  - name:               "Configure DB for SUT"
    command:
      argv:
        -               "{{ configure_sut_db }}"
    become:             yes
    become_user:        oracle
    when:
      -                 inventory_hostname in groups['database']
      -                 start_listener.stdout is defined
      -                 start_listener.stdout is not search(SUT_SERVICE_NAME)
    register:           configure_sut_db

  - name:               "Display output from Configure DB for SUT"
    debug:
      var:              configure_sut_db.stdout_lines
    when:               configure_sut_db.stdout_lines is defined

  - name:               "Stop firewall daemon"
    ansible.builtin.systemd:
      name:             firewalld
      state:            stopped
    become:             yes
    become_user:        root
    when:               inventory_hostname in groups['database']

  - name:               "Create HammerDB scripts"
    template:
      dest:             "{{ item }}"
      src:              "{{ item | basename }}.j2"
      mode:             "u+rwx"
    with_items:
      -                 "{{ create_hammerdb_schema_script }}"
      -                 "{{ create_tpcc_schema_parms }}"
    become:             yes
    become_user:        hammer
    when:               inventory_hostname in groups['client']

  - name:               "Count TPCC objects in DB for SUT"
    command:
      argv:
        -               "{{ count_tpcc_objects }}"
    become:             yes
    become_user:        oracle
    changed_when:       false
    when:
      -                 inventory_hostname in groups['database']
    register:           count_tpcc_objects

  - name:               "Output from Count TPCC objects in DB for SUT"
    debug:
      var:              count_tpcc_objects.stdout_lines
      verbosity:        0
    when:               count_tpcc_objects.stdout_lines is defined


  - name:               "Create HammerDB Schema"
    command:
      argv:
      -                 "{{ create_hammerdb_schema_script }}"
      chdir:            "{{ hammerdb_loc }}"
    register:           create_script_result
    become:             yes
    become_user:        hammer
    when:
      -                 inventory_hostname in groups['client']
      -                 count_tpcc_objects.stdout is defined
      -                 count_tpcc_objects.stdout is search('No objects defined for TPCC.')

  - name:               "Output from Creation of HammerDB Schema"
    debug:
      var:              create_script_result.stdout_lines
      verbosity:        0
    when:               create_script_result.stdout_lines is defined

...
