---
# ------------------------------------------------------------------------------
# Configure System Under Test (SUT) for use by HammerDB
# ------------------------------------------------------------------------------
- hosts:                all
  tasks:

  - name:               "Install required packages from repositories"
    dnf:
      name:
        -               tcl
      state:            present
    become:             yes
    become_user:        root

  - name:               "Install required packages using PIP"
    pip:
      name:
        -               "cx_Oracle"
      state:            present
    become:             yes
    become_user:        root

  - name:               "Start Oracle Listener and Database Instance"
    include_tasks:      startup_db.yml

  - name:               "Create DB Configuration Scripts"
    template:
      dest:             "{{ item }}"
      src:              "{{ item | basename }}.j2"
      mode:             "u+rwx"
    with_items:
      -                 "{{ configure_sut_db }}"
    become:             yes
    become_user:        oracle
    when:               inventory_hostname in groups['database']

  - name:               "Configure DB for SUT"
    command:
      argv:
        -               "{{ configure_sut_db }}"
    become:             yes
    become_user:        oracle
    when:               inventory_hostname in groups['database']
    register:           configure_sut_db

  - name:               "Display output from Configure DB for SUT"
    debug:
      var:              configure_sut_db.stdout_lines
    when:               configure_sut_db.stdout_lines is defined
...
