---
# ------------------------------------------------------------------------------
# Runs an iteration of the HammerDB performance test.
# ------------------------------------------------------------------------------

- hosts:                all
  any_errors_fatal:     true
  tasks:

  - name:               "Set plans"
    set_fact:
      plans:
      -                 "DEFAULT_PLAN"
      -                 "DEFAULT_PLAN"
      -                 "DEFAULT_PLAN"
      -                 "DEFAULT_PLAN"
      -                 "DEFAULT_PLAN"
      -                 "INTERNAL_PLAN"
      -                 "INTERNAL_PLAN"
      -                 "INTERNAL_PLAN"
      -                 "INTERNAL_PLAN"
      -                 "INTERNAL_PLAN"

  - name:               "Run original load test"
    import_tasks:       run_hammerdb_test_common.yml
...
