---
# ------------------------------------------------------------------------------
# Runs an iteration of the HammerDB performance test.
# ------------------------------------------------------------------------------

- hosts:                all
  any_errors_fatal:     true
  tasks:

  # ----------------------------------------------------------------------------
  # Load passwords from passwords/oracle.yml which has the following variables:
  # * pw_all
  # * pw_sys
  # * pw_system
  # * pw_pdbadmin
  #
  # >>>>>>> This file is deliberately NOT included in the GIT repository <<<<<<<
  # ----------------------------------------------------------------------------

  - name:               "Load passwords"
    include_vars:
      file:             "passwords/oracle.yml"
    no_log:             true

  - name:               "Start Oracle Listener and Database Instance"
    include_tasks:      startup_db.yml

  - name:               "Stop play for database hosts"
    meta:               end_host
    when:               inventory_hostname in groups['database']

  - name:               "Create HammerDB scripts"
    template:
      dest:             "{{ item }}"
      src:              "{{ item | basename }}.j2"
      mode:             "u+rwx"
    with_items:
      -                 "{{ run_hammerdb_script }}"
      -                 "{{ run_hammerdb_test_script }}"
      -                 "{{ custom_load_test_script }}"
    become:             yes
    become_user:        hammer
    when:               inventory_hostname in groups['client']

  - name:               "Run an Iteration of HammerDB Performance Test"
    command:
      argv:
      -                 "{{ run_hammerdb_script }}"
      -                 "{{ run_hammerdb_test_script }}"
    register:           test_run_result
    become:             yes
    become_user:        hammer
    when:               inventory_hostname in groups['client']

  - name:               "Output from HammerDB Performance Test"
    debug:
      var:              test_run_result.stdout_lines
      verbosity:        0
    when:               test_run_result.stdout_lines is defined

...
