---
# ------------------------------------------------------------------------------
# Global variables
# ------------------------------------------------------------------------------

oracle_user_home:       "/home/oracle"
nfs_loc:                "/opt/share/Software"

# ------------------------------------------------------------------------------
# Oracle Software Installation Options
# ------------------------------------------------------------------------------

install_group:          "oinstall"
inventory_location:     "/opt/app/oraInventory"
oracle_base:            "/opt/app/oracle"

# ------------------------------------------------------------------------------
# Global configuration settings
# ------------------------------------------------------------------------------

SUT_SERVICE_NAME:        "DEMO_DURAL.YAOCM.ID.AU"
tns_alias:               "{{ SUT_SERVICE_NAME.split('.')[0] }}"
globalDBName:            "DEMOCDB19C.YAOCM.ID.AU"
tpcc_tablespace_name:    "TPCCTAB"
tpcc_tablespace_datafile:
                         "{{ oracle_base }}/oradata/{{ globalDBName.split('.')[0] }}/tpcc/{{ tpcc_tablespace_name }}.dbf"
                         
original_data_rp:        "ORIGINAL_TPCC_DATA_RP"
...
